- Directory.Build.props
- Directory.Build.targets
Without these, building the repo can pick up a `Directory.Build.props/targets` that exist in a parent directory and cause downstream build failures.
This is going to be necessary for me to resolve: https://github.com/microsoft/ClangSharp/issues/195
> Adding empty Directory.Build.props/targets to avoid picking up external ones

- buildTransitive/Microsoft.Windows.SDK.Win32Metadata.props
- sources/nuget/Microsoft.Windows.SDK.Win32Metadata/Microsoft.Windows.SDK.Win32Metadata.nuspec
This prevents packages.config users from adding these two binaries as project content files.
Fixes #180
> Pack winmd+dll into package root instead of content folder

- sources/ClangSharpSourceToWinmd/MetadataSyntaxTreeCleaner.cs
Sets `isConst` to true for native type `LPCVOID` (aka. `const void*`).
After generating a new `Windows.Win32.winmd` file, I verified via ILSpy that `WriteFile` and `WriteFileEx` now properly show that the `lpBuffer` parameter is `[Const]`:
```C#
[DllImport("KERNEL32", ExactSpelling = true, SetLastError = true)]
public unsafe static extern BOOL WriteFile(
[In] HANDLE hFile,
[Optional][In][Const][NativeTypeInfo(UnmanagedType.LPArray, SizeParamIndex = 2)] void* lpBuffer,
...
);
[DllImport("KERNEL32", ExactSpelling = true, SetLastError = true)]
public unsafe static extern BOOL WriteFileEx(
[In] HANDLE hFile,
[Optional][In][Const][NativeTypeInfo(UnmanagedType.LPArray, SizeParamIndex = 2)] void* lpBuffer,
...
);
```
> fix issue #211

- scripts/CommonUtils.ps1
I noticed a small error when running `.\DoAll.ps1 -Clean`. PowerShell null is `$null`.
> Fix null => $null.

- generation/scraper/Partitions/DirectXShaderCompiler/main.cpp
- generation/scraper/Partitions/DirectXShaderCompiler/settings.rsp
dxcapi.h is shipped with the SDK and used to interact with `dxcompiler.dll`: https://github.com/microsoft/DirectXShaderCompiler.
> generation: Add DirectXShaderCompiler partition

- scripts/CommonUtils.ps1
- scripts/GenerateMetadataSource.ps1
These were found while testing https://github.com/microsoft/ClangSharp/pull/235.
In particular, it is useful to log the resolved path for `ClangSharpPInvokeGenerator` so it can be asserted to be the expected one (ClangSharp's CI test should override the global tool, for example).
Likewise, `Select-String` does not output a `string` by default, it outputs a `Microsoft.PowerShell.Commands.MatchInfo`: <https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-string?view=powershell-7.1#outputs> which does not have a Length property. It is expected that `-Raw` be passed if you want a `string`.
Additionally, if there is no match the result can be `$null`, which needs to be checked before getting the length.
> Log the ClangSharpPInvokeGenerator path and ensure the script doesn't fail for missing tools

- apidocs/Microsoft.Windows.SDK.Win32Docs/Microsoft.Windows.SDK.Win32Docs.targets
- azure-pipelines.yml
This gets the release notes link to be based on the tag that will eventually be created for this build rather than its own local version number.
> Fix release notes link in Win32Docs

- .gitignore
- sources/ClangSharpSourceToWinmd/ClangSharpSourceCompilation.cs
- sources/ClangSharpSourceToWinmd/MetadataSyntaxTreeCleaner.cs
- sources/ClangSharpSourceToWinmd/Program.cs
- sources/ClangSharpSourceToWinmd/Properties/launchSettings.json
- sources/Win32MetadataInterop/StaticLibraryAttribute.cs
- sources/msbuild/MetadataTasks/EmitWinmd.cs
- sources/msbuild/WebView2SampleDebug/WebView2SampleDebug.proj
- sources/msbuild/WebView2SampleDebug/main.cpp
- sources/msbuild/WebView2SampleDebug/nuget.config
- sources/msbuild/sdk/sdk.targets
- tests/SourceToWinmd/generation/remap.rsp
- tests/SourceToWinmd/source/generated/fake/test.cs
Per https://github.com/microsoft/windows-rs/pull/729, there are times when it would be nice to link a static lib instead of importing an entry-point from the DLL. None of the libraries in `Windows.Win32.winmd` currently support this since I think they're all system DLLs, but when #66 is finished this is a capability that would make sense to include.
I tested this manually with `Windows.Win32.winmd` by mapping `USER32` to a `FakeStaticUser32` LIB in the launch settings for `ClangSharpSourceToWinmd`, then I revived the `TestSource` target and codified the test mapping `MyDll` to `MyStaticLib`.
The result is a new attribute on all of the functions imported from `MyDll` which looks like `[StaticLibrary("MyStaticLib")]`. This is in addition to the existing `[DllImport("MyDll", ...]` attributes …
> Add a WebView2Sample with a StaticLibrary attribute mapping the DllImport name to an optional static library substitute

- sources/msbuild/MetadataTasks/ScanLibs.cs
- sources/msbuild/MetadataTasks/ScrapeHeaders.cs
This change adds null checks around the response files collection in the `ScrapeHeaders` task and libs property in the `ScanLibs` task. Without these checks, the tasks fail in scenarios where no applicable static libs were found and/or no libs were specified for scaping operations.
> Add null checks to ScrapeHeaders, ScanLibs to support no-lib scenarios

- apidocs/Microsoft.Windows.SDK.Win32Docs/buildTransitive/Microsoft.Windows.SDK.Win32Docs.props
- buildTransitive/Microsoft.Windows.SDK.Win32Metadata.props
- sources/msbuild/DiaSdk/buildTransitive/Microsoft.Dia.Win32Metadata.props
Instead of setting the `MicrosoftWindowsSdkWin32MetadataBasePath` msbuild property, which is a scalar and only allows one assignment, we now add to an msbuild item list so that projections (e.g. CsWin32) may consume many such metadata winmds in one build.
https://github.com/microsoft/CsWin32/pull/386 will consume this change.
> Create msbuild ProjectionMetadataWinmd item in package import

- generation/emitter/manual/Console.manual.cs
Fixes #642.
Added ENABLE_EXTENDED_FLAGS, ENABLE_AUTO_POSITION.
Also re-ordered the values to align with `consoleapi.h` for easier reading. I've tested for ABI impact via `Enum.GetValues` and observed no ill effects.
> Add missing console input mode flags

- sources/msbuild/GeneratorSample/GeneratorSample.proj
- sources/msbuild/GeneratorSampleDebug/GeneratorSampleDebug.proj
- sources/msbuild/WebView2SampleDebug/WebView2SampleDebug.proj
Without these, msbuild evaluation of these projects takes 2-4 minutes to search my entire hard drive for these files, given the base property isn't set at restore time.
> Add conditions to globbing

- sources/GeneratorSdk/sdk/sdk.props
- sources/GeneratorSdk/sdk/sdk.targets
We need to specify a version of Microsoft.Build.NoTargets when we Import it in the props and targets. This didn't fail the build because we have a global.json with Microsoft.Build.NoTargets in it, which most users won't have.
> Fixes #644 - Specify version of Microsoft.Build.NoTargets when doing Import

- sources/GeneratorSdk/samples/DiaSdk/Dia.manual.cs
- sources/GeneratorSdk/samples/DiaSdk/options.rsp
* Excludes anonymous enum __MIDL___MIDL_itf_dia2_0000_0034_0001; manually defines those HRESULTs.
* Excludes SymTagEnum enum; manually defines SymTag (subjectively) to prevent clashing with enumerator with name SymTagEnum.
* Corrects FPODATA remapping
For your reference:
```csharp
public enum __MIDL___MIDL_itf_dia2_0000_0034_0001
{
E_DIA_INPROLOG = -2140340124,
E_DIA_SYNTAX,
E_DIA_FRAME_ACCESS,
E_DIA_VALUE
}
```
> Add additional DIA excludes, types

- scripts/CommonUtils.ps1
Temporarily disables calling [Set-StrictMode](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-strictmode?view=powershell-7.2&WT.mc_id=WD-MVP-5002756) due to an issue discovered in [Visual Studio 17.1.0](https://developercommunity.visualstudio.com/t/launch-vsdevshell-no-longer-works-in-strict-mode/1673159).
Fixes build failures impacting #811.
> Temporarily disable PowerShell strict mode

- generation/WinSDK/Partitions/WinRT/main.cpp
- generation/WinSDK/Partitions/WinRT/settings.rsp
- scripts/BaselineWinmd/Windows.Win32.winmd
Adds missing CoreWindow interfaces, APIs to metadata (corewindow.h).
Fixes #830
Metadata diff
```
Windows.Win32.System.WinRT.ICoreWindowInterop not found in 1st winmd
Windows.Win32.System.WinRT.ICoreInputInterop not found in 1st winmd
Windows.Win32.System.WinRT.ICoreWindowComponentInterop not found in 1st winmd
Windows.Win32.System.WinRT.ICoreWindowAdapterInterop not found in 1st winmd
Windows.Win32.System.WinRT.Apis.CreateControlInput not found in 1st winmd
Windows.Win32.System.WinRT.Apis.CreateControlInputEx not found in 1st winmd
```
> Add missing CoreWindow APIs to Windows.Win32.System.WinRT

- generation/WinSDK/autoTypes.json
- scripts/BaselineWinmd/Windows.Win32.winmd
Adds `InvalidHandleValueAttribute` to HINSTANCE.
Did not also specify `-1` due to `#define HINST_COMMCTRL ((HINSTANCE)-1)` making `tagTBADDBITMAP` usage awkward.
Metadata diff:
```
Windows.Win32.Foundation.HINSTANCE : [RAIIFree(FreeLibrary),NativeTypedef] => [RAIIFree(FreeLibrary),InvalidHandleValue(0),NativeTypedef]
```
> Add InvalidHandleAttribute to HINSTANCE

- generation/WinSDK/enums.json
- scripts/BaselineWinmd/Windows.Win32.winmd
Combines send/recv flags into new `SEND_RECV_FLAGS` enumeration of integers and associates with send/recv functions.
Fixes: #849
Metadata diff:
```
Windows.Win32.Networking.WinSock.SEND_FLAGS not found in 2nd winmd
Windows.Win32.Networking.WinSock.SEND_RECV_FLAGS not found in 1st winmd
Windows.Win32.Networking.WinSock.Apis.MSG_PEEK not found in 2nd winmd
Windows.Win32.Networking.WinSock.Apis.MSG_WAITALL not found in 2nd winmd
Windows.Win32.Networking.WinSock.Apis.MSG_PUSH_IMMEDIATE not found in 2nd winmd
Windows.Win32.Networking.WinSock.Apis.recv : flags...Int32 => SEND_RECV_FLAGS
Windows.Win32.Networking.WinSock.Apis.send : flags...SEND_FLAGS => SEND_RECV_FLAGS
```
@mikebattista Can you double-check this satisfies what was discussed in #849? Thanks!
> Combine send/recv flags into new SEND_RECV_FLAGS enumeration

- generation/WinSDK/enums.json
- scripts/BaselineWinmd/Windows.Win32.winmd
Adds `[Flags]` to `JOB_OBJECT_CPU_RATE_CONTROL`.
Fixes: #873
Metadata diff:
```
Assembly (informational only) : [AssemblyVersion(22.0.3.46746)] => [AssemblyVersion(22.0.3.15463)]
Windows.Win32.System.JobObjects.JOB_OBJECT_CPU_RATE_CONTROL :  => [Flags]
```
> Annotate JOB_OBJECT_CPU_RATE_CONTROL as flags

- generation/WinSDK/emitter.settings.rsp
- scripts/BaselineWinmd/Windows.Win32.winmd
Changes `MOUSEINPUT::mouseData` data type from uint to int to support [documented `MOUSEEVENTF_WHEEL` semantics](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput#:~:text=a%20negative%20value%20indicates%20that%20the%20wheel%20was%20rotated%20backward%2C%20toward%20the%20user).
Fixes: #876
Metadata diff:
```
Assembly (informational only) : [AssemblyVersion(22.0.3.46746)] => [AssemblyVersion(22.0.3.15463)]
Windows.Win32.UI.Input.KeyboardAndMouse.MOUSEINPUT.mouseData...System.UInt32 => System.Int32
```
> Change MOUSEINPUT mouseData data type

- generation/WinSDK/emitter.settings.rsp
- scripts/BaselineWinmd/Windows.Win32.winmd
Improves return type of several ACLAPI functions.
Fixes: #884
Metadata diff:
```
Assembly (informational only) : [AssemblyVersion(22.0.3.46746)] => [AssemblyVersion(22.0.3.15463)]
Windows.Win32.Security.Authorization.Apis.GetNamedSecurityInfoA : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetNamedSecurityInfoW : return...UInt32 => WIN32_ERROR
Windows.Win32.Security.Authorization.Apis.GetSecurityInfo : return...UInt32 => WIN32_ERROR
```
> Change return type for several aclapi functions

- generation/WinSDK/manual/WinRT.cs
- generation/WinSDK/scraper.settings.rsp
- scripts/BaselineWinmd/Windows.Win32.winmd
Adds a manual definition of `HSTRING_HEADER` to clean up the awkward union.
Fixes: #886 
Before:
```csharp
public struct HSTRING_HEADER
{
[StructLayout(LayoutKind.Explicit)]
public struct _Reserved_e__Union
{
[FieldOffset(0)]
public unsafe void* Reserved1;
[FieldOffset(0)]
public CHAR[] Reserved2;
}
public _Reserved_e__Union Reserved;
}
```
After:
```csharp
public struct HSTRING_HEADER
{
public uint flags;
public uint length;
public uint padding1;
public uint padding2;
public IntPtr data;
}
```
Metadata diff:
```
Windows.Win32.System.WinRT.HSTRING_HEADER.Reserved not found in 2nd winmd
Windows.Win32.System.WinRT.HSTRING_HEADER.flags not found in 1st winmd
Windows.Win32.System.WinRT.HSTRING_HEADER.length not found in 1st winmd
Windows.Win32.System.WinRT.HSTRING_HEADER.padding1 not found in …
```
> Provide manual definition of HSTRING_HEADER

- scripts/BaselineWinmd/Windows.Win32.winmd
- sources/MetadataUtils/ConstantsScraper.cs
Tweaks the regular expression looking for `MAKEINTRESOURCE` matches to also find `A` and `W` variants.
Fixes: #968
Example:
```cpp
#define TD_WARNING_ICON         MAKEINTRESOURCEW(-1)
#define TD_ERROR_ICON           MAKEINTRESOURCEW(-2)
#define TD_INFORMATION_ICON     MAKEINTRESOURCEW(-3)
#define TD_SHIELD_ICON          MAKEINTRESOURCEW(-4)
```
Metadata diff:
```
Windows.Win32.UI.Controls.Apis.TD_WARNING_ICON not found in 1st winmd
Windows.Win32.UI.Controls.Apis.TD_ERROR_ICON not found in 1st winmd
Windows.Win32.UI.Controls.Apis.TD_INFORMATION_ICON not found in 1st winmd
Windows.Win32.UI.Controls.Apis.TD_SHIELD_ICON not found in 1st winmd
```
> Adjust regex for MAKEINTRESOURCE[AW] usage

- generation/WinSDK/manual/FileSystem.cs
- scripts/BaselineWinmd/Windows.Win32.winmd
Adds missing `MAXIMUM_REPARSE_DATA_BUFFER_SIZE` constant manually for now. Longer term, it'd be nice if the constant scraper supported some basic expression evaluation.
Fixes: #966
> Add MAXIMUM_REPARSE_DATA_BUFFER_SIZE constant

- DoAll.ps1
- scripts/Get-RequiredWorkloads.ps1
Without this change, DoAll.ps1 could execute a bunch of work and ultimately fail to build a vcxproj with a misleading error message.
> Force rapid discovery of missing VS required components for the build

- scripts/BaselineWinmd/Windows.Win32.winmd
- sources/ClangSharpSourceToWinmd/MetadataSyntaxTreeCleaner.cs
Extends regular expression to correctly capture `SAL_readableTo` / `SAL_writeableTo` buffer size information if `_Old_` intrinsic is in use (e.g. `Name=SAL_readableTo; p1=byteCount(_Old_(cbKeyObject))`).
Fixes: #1010
Metadata diff:
```
Windows.Win32.System.Com.Urlmon.IInternetHostSecurityManager.ProcessUrlAction : pPolicy : [Out] => [Out,NativeArrayInfo(CountParamIndex=2)]
Windows.Win32.Graphics.Dxgi.IDXGIDevice2.ReclaimResources : pDiscarded : [Optional,Out] => [Optional,Out,NativeArrayInfo(CountParamIndex=0)]
Windows.Win32.Graphics.Dxgi.IDXGIDevice4.ReclaimResources1 : pResults : [Out] => [Out,NativeArrayInfo(CountParamIndex=0)]
Windows.Win32.Security.Cryptography.Apis.BCryptGenerateSymmetricKey : pbKeyObject : [Optional,Out] => [Optional,Out,MemorySize(BytesParamIndex=3)] …
```
> Compensate for _Old_ intrinsic during SAL writableTo/readableTo capture

- generation/WinSDK/Partitions/WinProg/settings.rsp
- generation/WinSDK/inc/windows.fixed.h
- generation/WinSDK/manual/WinProg.cs
- scripts/BaselineWinmd/Windows.Win32.winmd
The #define DeleteFile to DeleteFileA in fileaph.h was messing up the struct and a parameter name.
Fixes #986
> Don't let the #define DeleteFile mess up field and param names

- generation/WinSDK/enums.json
- scripts/ChangesSinceLastRelease.txt
Fixes: 
- https://github.com/microsoft/win32metadata/issues/1036
- https://github.com/microsoft/win32metadata/issues/1045
```
Windows.Win32.Graphics.Gdi.TEXT_ALIGN_OPTIONS :  => [Flags]
Windows.Win32.Graphics.Gdi.Apis.GetROP2 : return...Int32 => R2_MODE
Windows.Win32.Graphics.Gdi.Apis.GetTextAlign : return...UInt32 => TEXT_ALIGN_OPTIONS
```
> Changes R2_MODE and TEXT_ALIGN_OPTIONS

- azure-pipelines.yml
- scripts/AddRemapsFromApiCsv.ps1
- scripts/BuildMetadataBin.ps1
- scripts/CommonUtils.ps1
- scripts/ConvertMidlAttributesToSalAnnotations.ps1
- scripts/CreateApiInfoCsv.ps1
- scripts/CreateNameToNamespaceMappings.ps1
- scripts/CreateProcLibMappingForAllLibs.ps1
- scripts/CreateSupportedOSPlatformRsp.ps1
- scripts/CreateUsingsForGeneratedSources.ps1
- scripts/DisplayPossibleMappings.ps1
- scripts/DoPackages.ps1
- scripts/DoSamples.ps1
- scripts/DoTests.ps1
- scripts/GenerateMetadataSource.ps1
- scripts/Install-AllSoftware.ps1
- scripts/RecompileIdlFilesForScraping.ps1
- scripts/TestHeaderFileCoverage.ps1
- scripts/TestWinmdBinary.ps1
- sources/ConstantsScraper/Program.cs
- sources/GeneratorSdk/sdk/sdk.targets
I needed some of these changes to diagnose the enum parsing failures from #1228. Since they are overall goodness, I wanted to share.
-  Capture msbuild binlogs in local builds and in the pipeline
- Emit constants scraper errors in the console log
Errors should be written to STDERR, and msbuild should invoke tools such that STDERR gets treated with high priority.
- Use powershell `Write-Host` and `Write-Error` as appropriate
This avoids needing to use terminal escape codes to colorize output.
This directs errors to the STDERR stream as appropriate.
> Logging improvements

- generation/WinSDK/enums.json
- scripts/ChangesSinceLastRelease.txt
I have been going through the Windows.Win32.System.Ole.Api namespace and adding enums.
Fixes: #1090 (doesn't cover it entirely, issue needs discussion)
Fixes: #1091
Fixes: #1144
Fixes: #1155
Fixes: #1154
```
Windows.Win32.System.Com.IDLDESC.wIDLFlags...System.UInt16 => Windows.Win32.System.Com.IDLFLAGS
Windows.Win32.System.Com.IDLFLAGS added
Windows.Win32.System.Com.IDLFLAGS.IDLFLAG_FIN added
Windows.Win32.System.Com.IDLFLAGS.IDLFLAG_FLCID added
Windows.Win32.System.Com.IDLFLAGS.IDLFLAG_FOUT added
Windows.Win32.System.Com.IDLFLAGS.IDLFLAG_FRETVAL added
Windows.Win32.System.Com.IDLFLAGS.IDLFLAG_NONE added
Windows.Win32.System.Com.IMPLTYPEFLAGS added
Windows.Win32.System.Com.IMPLTYPEFLAGS.IMPLTYPEFLAG_FDEFAULT added
Windows.Win32.System.Com.IMPLTYPEFLAGS.IMPLTYPEFLAG_FDEFAULTVTABLE added …
```
> Adding enums for OLE

- generation/WinSDK/enums.json
- scripts/ChangesSinceLastRelease.txt
Fixes #1189
Fixes: #1190
Fixes: #1171
Fixes: #1172
```
Windows.Win32.UI.Controls.Apis.LVTVIF_AUTOSIZE removed
Windows.Win32.UI.Controls.Apis.LVTVIF_EXTENDED added
Windows.Win32.UI.Controls.Apis.LVTVIF_FIXEDHEIGHT removed
Windows.Win32.UI.Controls.Apis.LVTVIF_FIXEDSIZE removed
Windows.Win32.UI.Controls.Apis.LVTVIF_FIXEDWIDTH removed
Windows.Win32.UI.Controls.Apis.LVTVIM_COLUMNS removed
Windows.Win32.UI.Controls.Apis.LVTVIM_LABELMARGIN removed
Windows.Win32.UI.Controls.Apis.LVTVIM_TILESIZE removed
Windows.Win32.UI.Controls.LVTILEVIEWINFO_FLAGS :  => [Flags]
Windows.Win32.UI.Controls.LVTILEVIEWINFO_FLAGS.LVTVIF_AUTOSIZE added
Windows.Win32.UI.Controls.LVTILEVIEWINFO_FLAGS.LVTVIF_EXTENDED removed
Windows.Win32.UI.Controls.LVTILEVIEWINFO_FLAGS.LVTVIF_FIXEDHEIGHT added …
```
> `MW_FILTERMODE_ `/`EVCF_`/`LVTILEVIEWINFO_FLAGS`

- generation/WinSDK/enums.json
- scripts/ChangesSinceLastRelease.txt
Fixes: #1213
```
Windows.Win32.Graphics.Gdi.Apis.CreateFontA : iClipPrecision...FONT_CLIP_PRECISION => UInt32
Windows.Win32.Graphics.Gdi.Apis.CreateFontA : iOutPrecision...FONT_OUTPUT_PRECISION => UInt32
Windows.Win32.Graphics.Gdi.Apis.CreateFontA : iPitchAndFamily...FONT_PITCH_AND_FAMILY => UInt32
Windows.Win32.Graphics.Gdi.Apis.CreateFontA : iQuality...FONT_QUALITY => UInt32
Windows.Win32.Graphics.Gdi.Apis.CreateFontW : iClipPrecision...FONT_CLIP_PRECISION => UInt32
Windows.Win32.Graphics.Gdi.Apis.CreateFontW : iOutPrecision...FONT_OUTPUT_PRECISION => UInt32
Windows.Win32.Graphics.Gdi.Apis.CreateFontW : iPitchAndFamily...FONT_PITCH_AND_FAMILY => UInt32
Windows.Win32.Graphics.Gdi.Apis.CreateFontW : iQuality...FONT_QUALITY => UInt32
Windows.Win32.Graphics.Gdi.Apis.DEFAULT_PITCH removed …
```
> Fix LOGFONTW/LOGFONTA

- generation/WinSDK/emitter.settings.rsp
- scripts/ChangesSinceLastRelease.txt
Fixes: #1279 
Metadata diff:
```
Windows.Win32.UI.Shell.PropertiesSystem.Apis.SHGetPropertyStoreFromParsingName : ppv : [Out] => [ComOutPtr,Out]
```
> Add ComOutPtr to SHGetPropertyStoreFromParsingName

- generation/WinSDK/enums.json
- scripts/ChangesSinceLastRelease.txt
Fixes: #1283
Metadata diff:
```
Windows.Win32.UI.Shell.Apis.SHGetStockIconInfo : uFlags...UInt32 => SHGSI_FLAGS
Windows.Win32.UI.Shell.Apis.SHGSI_ICONLOCATION removed
Windows.Win32.UI.Shell.SHGSI_FLAGS added
Windows.Win32.UI.Shell.SHGSI_FLAGS.SHGSI_ICON added
Windows.Win32.UI.Shell.SHGSI_FLAGS.SHGSI_ICONLOCATION added
Windows.Win32.UI.Shell.SHGSI_FLAGS.SHGSI_LARGEICON added
Windows.Win32.UI.Shell.SHGSI_FLAGS.SHGSI_LINKOVERLAY added
Windows.Win32.UI.Shell.SHGSI_FLAGS.SHGSI_SELECTED added
Windows.Win32.UI.Shell.SHGSI_FLAGS.SHGSI_SHELLICONSIZE added
Windows.Win32.UI.Shell.SHGSI_FLAGS.SHGSI_SMALLICON added
Windows.Win32.UI.Shell.SHGSI_FLAGS.SHGSI_SYSICONINDEX added
```
> Add in SHGSI Enum

- generation/WinSDK/enums.json
- scripts/ChangesSinceLastRelease.txt
Fixes: #1325
Sample from original reporter, tweaked to validate the struct:
```rust
use windows::Win32::Graphics::Gdi::*;
fn main() {
let mut dm = DEVMODEA::default();
dm.dmSize = std::mem::size_of_val(&dm) as u16;
assert_eq!(dm.dmSize, 156);
let b = unsafe {
EnumDisplaySettingsExA(
windows::core::PCSTR::null(),
ENUM_CURRENT_SETTINGS,
&mut dm,
0u32,
)
};
println!("Result: {:?}", b);
println!("dm.dmSize: {:?}", dm.dmSize);
println!("dmBitsPerPel: {:?}", dm.dmBitsPerPel);
println!("dmPelsWidth: {:?}", dm.dmPelsWidth);
println!("dmPelsHeight: {:?}", dm.dmPelsHeight);
println!("dmDisplayFrequency: {:?}", dm.dmDisplayFrequency);
println!("others");
println!("dmSpecVersion: {:?}", dm.dmSpecVersion);
println!("dmDriverVersion: {:?}", dm.dmDriverVersion);
println!("dmDriverExtra: {:?}", …
```
> Adjust DEVMODE structure fields

- generation/WinSDK/enums.json
- scripts/ChangesSinceLastRelease.txt
Fixes #1148
```
Windows.Win32.System.Ole.CLIPBOARD_FORMATS added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_BITMAP added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_DIB added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_DIBV5 added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_DIF added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_DSPBITMAP added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_DSPENHMETAFILE added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_DSPMETAFILEPICT added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_DSPTEXT added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_ENHMETAFILE added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_GDIOBJFIRST added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_GDIOBJLAST added
Windows.Win32.System.Ole.CLIPBOARD_FORMATS.CF_HDROP added …
```
> Add enum for cfFormat

- generation/WinSDK/enums.json
- scripts/ChangesSinceLastRelease.txt
Fixes #1146
```
Unknown differences found:
Windows.Win32.System.Ole.Apis.OLEIVERB_DISCARDUNDOSTATE removed
Windows.Win32.System.Ole.Apis.OLEIVERB_HIDE removed
Windows.Win32.System.Ole.Apis.OLEIVERB_INPLACEACTIVATE removed
Windows.Win32.System.Ole.Apis.OLEIVERB_OPEN removed
Windows.Win32.System.Ole.Apis.OLEIVERB_PRIMARY removed
Windows.Win32.System.Ole.Apis.OLEIVERB_SHOW removed
Windows.Win32.System.Ole.Apis.OLEIVERB_UIACTIVATE removed
Windows.Win32.System.Ole.OLEIVERB added
Windows.Win32.System.Ole.OLEIVERB.OLEIVERB_DISCARDUNDOSTATE added
Windows.Win32.System.Ole.OLEIVERB.OLEIVERB_HIDE added
Windows.Win32.System.Ole.OLEIVERB.OLEIVERB_INPLACEACTIVATE added
Windows.Win32.System.Ole.OLEIVERB.OLEIVERB_OPEN added
Windows.Win32.System.Ole.OLEIVERB.OLEIVERB_PRIMARY added …
```
> Add enum for OLEIVERB

- Directory.Build.props
- azure-pipelines.yml
- sources/ClangSharpSourceToWinmd/ClangSharpSourceToWinmd.csproj
- sources/ConstantsScraper/ConstantsScraper.csproj
- sources/GeneratorSdk/MetadataTasks/MetadataTasks.csproj
- sources/MetadataUtils/MetadataUtils.csproj
- sources/Win32MetadataInterop/Win32MetadataInterop.csproj
- sources/WinmdUtils/WinmdUtils.csproj
- tests/ClangSharpSourceToWinmdTests/ClangSharpSourceToWinmdTests.csproj
- tests/MetadataUtils.Tests/MetadataUtils.Tests.csproj
- tests/TestCommon/TestCommon.csproj
- tests/VtablesFromPdb/VtablesFromPdb.csproj
- tests/Windows.Win32.Tests/Windows.Win32.Tests.csproj
We need to build it, sign it, then pack it.
> Sign the Microsoft.Windows.Sdk.Win32Docs.dll assembly

- scripts/ChangesSinceLastRelease.txt
- sources/ClangSharpSourceToWinmd/ClangSharpSourceWinmdGenerator.cs
Fixes #1389 and picks up some stragglers.
Metadata diff:
```
Windows.Win32.Networking.WinHttp.URL_COMPONENTS.nPort...System.UInt16 => Windows.Win32.Networking.WinHttp.INTERNET_PORT
Windows.Win32.Networking.WinHttp.WINHTTP_PROXY_RESULT_ENTRY.ProxyPort...System.UInt16 => Windows.Win32.Networking.WinHttp.INTERNET_PORT
Windows.Win32.Networking.WinInet.Apis.GopherCreateLocatorA : nServerPort...UInt16 => INTERNET_PORT
Windows.Win32.Networking.WinInet.Apis.GopherCreateLocatorW : nServerPort...UInt16 => INTERNET_PORT
Windows.Win32.Networking.WinInet.Apis.InternetConnectA : nServerPort...UInt16 => INTERNET_PORT
Windows.Win32.Networking.WinInet.Apis.InternetConnectW : nServerPort...UInt16 => INTERNET_PORT
Windows.Win32.Networking.WinInet.URL_COMPONENTSA.nPort...System.UInt16 => …
```
> Add support for remapping short integers

- generation/WinSDK/enums.json
- scripts/ChangesSinceLastRelease.txt
Fixes #1395
Adds enum for `uMapType` parameter.
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeyexw
diff:
```
Windows.Win32.UI.Input.KeyboardAndMouse.Apis.MapVirtualKeyA : uMapType...UInt32 => MAP_VIRTUAL_KEY_TYPE
Windows.Win32.UI.Input.KeyboardAndMouse.Apis.MapVirtualKeyExA : uMapType...UInt32 => MAP_VIRTUAL_KEY_TYPE
Windows.Win32.UI.Input.KeyboardAndMouse.Apis.MapVirtualKeyExW : uMapType...UInt32 => MAP_VIRTUAL_KEY_TYPE
Windows.Win32.UI.Input.KeyboardAndMouse.Apis.MapVirtualKeyW : uMapType...UInt32 => MAP_VIRTUAL_KEY_TYPE
Windows.Win32.UI.Input.KeyboardAndMouse.MAP_VIRTUAL_KEY_TYPE added
Windows.Win32.UI.Input.KeyboardAndMouse.MAP_VIRTUAL_KEY_TYPE.MAPVK_VK_TO_CHAR added
Windows.Win32.UI.Input.KeyboardAndMouse.MAP_VIRTUAL_KEY_TYPE.MAPVK_VK_TO_VSC added …
```
> Add `MAP_VIRTUAL_KEY_TYPE` for `MAPVK_` constants to MapVirtualKey functions

- sources/MetadataUtils/MetadataUtils.csproj
- sources/Win32MetadataInterop/Win32MetadataInterop.csproj
I regularly run into build issues where the build filters resolve to false on two (of three) projects that rely on the AllowUnsafeCode property, resulting in build failures. This change just removes the conditions to make the build more reliable on local machines.
> removing conditional filters for unsafe code property

- generation/WinSDK/emitter.settings.rsp
- scripts/ChangesSinceLastRelease.txt
This is currently a `UINT` followed by a comment stating the actual enumeration type that contains the possible flag bits.
> Mark `DXGI_SWAP_CHAIN_DESC1::Flags` as `DXGI_SWAP_CHAIN_FLAG` type

- README.md
We've moved the Dart projection to a separate org repo, also including WinRT projections, so updating the link to match.
> Change URL for Dart projection

- generation/WinSDK/emitter.settings.rsp
Corrected `ICompositionTexture` external assembly reference (10 -> 15). Also sorted and grouped the `typeImport` lines for better visibility.
Fixes: #1760
> Correct external contract assembly references

- generation/WinSDK/emitter.settings.rsp
- scripts/ChangesSinceLastRelease.txt
This commit fixes the IoRing function return types. `PopIoRingCompletion` function has multiple success values which should be reflected in the metadata.
> fix: IoRing return types

- generation/WinSDK/emitter.settings.rsp
- scripts/ChangesSinceLastRelease.txt
> Correct ICompositionTexture reference

- sources/ClangSharpSourceToWinmd/ClangSharpSourceWinmdGenerator.cs
While trying to generate my own bindings, `ClangSharpSourceToWinmd` was reporting the following error:
```
error CS0648: '' is a type not supported by the language
```
I tracked it down to a method in the current compilation using a struct from a referenced WinMD (let's call this "Middle.winmd") which had a field from another WinMD (let's call it "Base.winmd"). Looking at the winmd files in ildasm, Middle.winmd was missing a reference to Base.winmd, so there was no way for the current compilation to know where referenced types came from, despite the current compilation referencing both Middle.winmd and Base.winmd.
The fix for this is to add an assembly reference to all assemblies passed in via `--ref`
> Add references for all assemblies passed in via `--ref`

- generation/WinSDK/autoTypes.json
- scripts/ChangesSinceLastRelease.txt
Addresses missing `InvalidHandleValue` metadata for `RAIIFree`-marked types mentioned in #1891.
> Add additional InvalidHandleValues metadata

- sources/ConstantsScraper/Program.cs
- sources/MetadataUtils/ConstantWriter.cs
Although `ConstantsScraper` can reference named constants from other header files, if that other header file's constants were placed into a different namespace (e.g., in a different WinMD file) then the C# generated is invalid.
This change adds a new option `--useConstantsFrom` that can be used to generate `using static` declarations for other namespaces that the current C# file may reference.
> Add an option to ConstantsScraper to import constants from another namespace

- tests/MetadataUtils.Tests/ConstantsScraperTests.cs
#1890 broke the ConstantsScraper tests by removing an extra newline at the beginning of emitted files if there is no header text or `using` declarations to emit.
> Fix ConstantsScraper tests

- generation/WinSDK/emitter.settings.rsp
- scripts/ChangesSinceLastRelease.txt
Fixes: #1881
Removes native array information metadata from `ScriptStringAnalyse::piDx`. Further discussion in aforementioned issue thread.
> Remove incomplete metadata for ScriptStringAnalyse

- sources/ClangSharpSourceToWinmd/ClangSharpSourceWinmdGenerator.cs
- sources/MetadataUtils/WinmdUtils.cs
- sources/WinmdUtils/Program.cs
- tests/MetadataUtils.Tests/WinmdUtilsTests.cs
We were seeing a crash in `ClangSharpSourceToWinmd` when we had an interface inheriting another interface from a different assembly:
```
3001>Unhandled exception: System.InvalidOperationException: Sequence contains no matching element
3001>   at System.Linq.ThrowHelper.ThrowNoMatchException()
3001>   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
3001>   at MetadataUtils.WinmdUtils.InternalGetImplementedMethodCount(TypeDefinition typeDef)
3001>   at MetadataUtils.WinmdUtils.GetTypes()+MoveNext()
3001>   at ClangSharpSourceToWinmd.ClangSharpSourceWinmdGenerator.<PopulateMetadataBuilder>g__GatherInterfaceTypes|60_1()
3001>   at ClangSharpSourceToWinmd.ClangSharpSourceWinmdGenerator.PopulateMetadataBuilder()
3001>   at …
```
> When finding a type def from a type ref, search all assemblies

- sources/WinmdUtils/Program.cs
PR #1919 introduced a test failure since it was passing an empty list for `allWinmds`, fix is to pass a list containing the current WinMD.
> Fix test failures

- generation/WinSDK/emitter.settings.rsp
- scripts/ChangesSinceLastRelease.txt
Fixes: #1941
Adds `CanReturnMultipleSuccessValues` to `IPropertyStoreCapabilities::IsPropertyWritable` method. This method can return either `S_OK` or `S_FALSE`. Also removes the optional Attribute suffix on a few entries as cleanup.
> Add attribute on IPropertyStoreCapabilities::IsPropertyWritable

- AzurePipelinesTemplates/win32metadata-onebranch.yml
Commit messages are often too long and have disallowed characters, which interfered with the pipeline running. They arguably do not belong in the ADO pipeline build number anyways. This change removes them.
> Remove commit name from pipeline build number

- AzurePipelinesTemplates/win32docs-onebranch.yml
- AzurePipelinesTemplates/win32metadata-checkout.yml
- AzurePipelinesTemplates/win32metadata-onebranch.yml
- Disable submodule checkout for non-doc builds to speed up pipeline runs
- Fix the Pipeline Version to include the '-preview' for preview builds by using nbgv's CloudBuildNumber instead GitBuildVersionSimple
- Add a message to the Pipeline Version for PR builds to include the branch name and commit message.
- There are restrictions on how long and what characters can be part of the "Pipeline Version", but this is a big improvement over just having a major.minor.patch number set. ADO normally allows for both a Version and a Message, but setting the Message after the pipeline is initialized (which is our use case since this github repo is only an ADO resource) isn't supported yet, so we insert this information into the Pipeline Version. 
- The Pipeline Version is re-used in the Official …
> Disable submodules where not needed and add pipeline message for PR builds

- generation/WinSDK/emitter.settings.rsp
- scripts/ChangesSinceLastRelease.txt
Partially fixes #1961.
Adjusts PMPRADMINCONNECTIONHANGUPNOTIFICATION3 parameter 4 to align with docs. Appears to be a SDK bug (mprapi.h, 26100).
> Correct PMPRADMINCONNECTIONHANGUPNOTIFICATION3 parameter 4

- generation/WinSDK/emitter.settings.rsp
- scripts/ChangesSinceLastRelease.txt
- sources/ClangSharpSourceToWinmd/MetadataSyntaxTreeCleaner.cs
Related: #1961
Removed `StructSizeField` from `BLOB` and `BSTRBLOB` as these were mistakenly flagged due to the `cbSize` fields. The logic that adds this attribute has also been moved up to allow proper remapping/removal of this attribute.
> Remove StructSizeField from BLOB, BSTRBLOB

- generation/WinSDK/autoTypes.json
- scripts/ChangesSinceLastRelease.txt
Fixes: #1985, fixes: #1986
Removing RAIIFree attribute from PSID due to ambiguous freeing semantics for PSID. See AllocateAndInitializeSid vs ConvertStringSidToSid.
> Remove RAIIFree attribute from PSID

- .github/dependabot.yml
- apidocs/Microsoft.Windows.SDK.Win32Docs/Microsoft.Windows.SDK.Win32Docs.csproj
- apidocs/ScrapeDocs/ScrapeDocs.csproj
**Issue:**
Dependabot [found ](https://github.com/microsoft/win32metadata/security/dependabot/6) 1 NuGet package that requires updating to address security vulnerabilities.
**Fix:**
Update MessagePack to latest stable release to address security vulnerabilities.
Also add a [dependabot.yml](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) to override the default behavior and ensure proper NuGet feed URL.
**How verified:**
Built both projects in Visual Studio to confirm projects built with no issues.
> Address dependabot alerts about MessagePack NuGet package

- CONTRIBUTING.md
- generation/WinSDK/Windows.Win32.proj
- scripts/CommonUtils.ps1
- scripts/Install-DotNetTool.ps1
- sources/GeneratorSdk/MetadataTasks/ScrapeHeaders.cs
- sources/GeneratorSdk/MetadataTasks/TaskUtils.cs
- sources/GeneratorSdk/samples/DiaSdk/Microsoft.Dia.Win32Metadata.nuspec
- sources/GeneratorSdk/samples/GeneratorSampleDebug/GeneratorSampleDebug.proj
- sources/GeneratorSdk/sdk/sdk.props
- sources/GeneratorSdk/sdk/sdk.targets
**Issue:**
NuGet.config was not being taking into account when running Install-DotNetTool.ps1.
**Fix:**
Pass NuGet.config into Install-DotNetTool.ps1. 
Since, Install-DotNetTool.ps1 now required a NuGet.config file winmdgenerator needed to be updated to supply a NuGet.config as Install-DotNetTool.ps1 is called to install [ClangSharpPInvokeGenerator](https://github.com/microsoft/win32metadata/blob/35d6cb24f7f9c2e6c16e1855384400744d2643eb/sources/GeneratorSdk/MetadataTasks/ScrapeHeaders.cs#L186). 
To allow for flexibility by consumers **NuGetPackageSource** build property was added to Code, Props and targets to enable overriding from the default package source. CONTRIBUTING.MD was also generated to mention the NuGetPackageSource override.
**How tested:**
1. Ran .\DoAll.ps1 -clean and …
> Update Install-DotNetTool.ps1 to use repos NuGet.config

- AzurePipelinesTemplates/win32metadata-onebranch.yml
**Issue:**
#2013 broke official build pipeilnes
**Root Cause:**
-NuGetConfigFile wasn't passed into Install-DotNetTools.ps1 like in the wdkmetadata pipeline: https://github.com/microsoft/wdkmetadata/blob/599d7365376dcf70062dbfde11f91cb80b1e56bc/AzurePipelinesTemplates/wdkmetadata-onebranch.yml#L55
**Fix:**
Apply same NuGetConfigFile change as wdkmetadata to pipeline yaml.
**How verified:**
1. Ran PR build and confirmed success with fix.
> Apply same NuGetConfigFile change as wdkmetadata to pipeline yaml

- AzurePipelinesTemplates/win32docs-onebranch.yml
- AzurePipelinesTemplates/win32metadata-onebranch.yml
- scripts/BuildMetadataBin.ps1
- scripts/CommonUtils.ps1
- scripts/GenerateMetadataSource.ps1
- scripts/Install-DotNetTool.ps1
This change fixes nbgv pulling from nuget.org in the dos portion of the build.  I've also included other updates from wdkmetadata that improve log retention and separation of restore/build tasks (https://github.com/microsoft/wdkmetadata/pull/84).
> nbgv still pulled from nuget.org
