microsoft/win32metadata

release.yml
This creates a release and pushes the NuGet package to nuget.org.
=> Adding release pipeline

generation/emitter/autoTypes.rsp
=> Add HPOWERNOTIFY as IntPtr type

.gitattributes
Users will need to follow the instructions here to set up git lfs for their account: https://git-lfs.github.com/
=> Make .zip, .winmd use git lfs

.gitignore, azure-pipelines.yml, generation/scraper/Partitions/Js/settings.rsp, sources/ClangSharpSourceToWinmd/ClangSharpSourceCompilation.cs, sources/ClangSharpSourceToWinmd/CrossArchSyntaxMap.cs, sources/ClangSharpSourceToWinmd/CrossArchTreeMerger.cs, sources/ClangSharpSourceToWinmd/MetadataSyntaxTreeCleaner.cs, sources/ClangSharpSourceToWinmd/NamesToCorrectNamespacesMover.cs, sources/ClangSharpSourceToWinmd/Program.cs
This changes the pipeline to use the public vm image. It also includes some memory perf improvements because it was running out of memory on the public vm image.
=> Change the pipeline to use the public vm image

azure-pipelines.yml
Get rid of signing and pushing for PR builds in the pipeline.
=> Get rid of signing and pushing for PR builds

sources/ClangSharpSourceToWinmd/CrossArchSyntaxMap.cs, sources/msbuild/MetadataTasks/EmitWinmd.cs
- Fix two build warnings
- Convert EmitWinmd to a ToolTask
=> MSBuild task improvements

generation/WinSDK/Partitions/HostCompute/main.cpp, generation/WinSDK/Partitions/HostCompute/settings.rsp, generation/WinSDK/autoTypes.json, scripts/BaselineWinmd/Windows.Win32.winmd, sources/ClangSharpSourceToWinmd/GeneratorDiagnostic.cs, sources/ClangSharpSourceToWinmd/NativeTypedefStructsCreator.cs, sources/ClangSharpSourceToWinmd/Program.cs
* Adding a partition for HostCompute
* Fixing the winmd generator to show an error if the typedef creator throws an exception
=> Adding a partition for HostCompute

generation/WinSDK/autoTypes.json, scripts/BaselineWinmd/Windows.Win32.winmd
After removing the incorrect `PSECURITY_DESCRIPTOR` mapping, we left behind an unsightly bare pointer. This change introduces a new NativeTypeDef to address that.
Fixes: #835
Metadata diff
```
Windows.Win32.Security.Authorization.UI.ISecurityInformation.GetSecurity : ppSecurityDescriptor...Void** => PSECURITY_DESCRIPTOR*
Windows.Win32.Security.Authorization.UI.ISecurityInformation.SetSecurity : pSecurityDescriptor...Void* => PSECURITY_DESCRIPTOR
Windows.Win32.Security.Authorization.UI.ISecurityInformation.SetSecurity : pSecurityDescriptor : [In,Out] => [In]
Windows.Win32.Security.Authorization.UI.IEffectivePermission.GetEffectivePermission : pSD...Void* => PSECURITY_DESCRIPTOR
Windows.Win32.Security.Authorization.UI.IEffectivePermission.GetEffectivePermission : pSD : [In,Out] => [In] …
```
=> Add PSECURITY_DESCRIPTOR NativeTypeDef

CONTRIBUTING.md, Directory.Build.props, DoAll.ps1, apidocs/Microsoft.Windows.SDK.Win32Docs/Microsoft.Windows.SDK.Win32Docs.csproj, apidocs/ScrapeDocs/ScrapeDocs.csproj, azure-pipelines.yml, generation/WinSDK/Windows.Win32.proj, global.json, scripts/CommonUtils.ps1, scripts/Get-RequiredWorkloads.ps1, scripts/Get-VSPath.ps1, scripts/Get-VSWhereBaseArgs.ps1, scripts/GetVcDirPath.ps1, scripts/Install-VS.ps1, sources/ClangSharpSourceToWinmd/ClangSharpSourceToWinmd.csproj, sources/ConstantsScraper/ConstantsScraper.csproj, sources/GeneratorSdk/MetadataTasks/MetadataTasks.csproj, sources/GeneratorSdk/nuget/BuildSdk.nuspec, sources/GeneratorSdk/nuget/BuildSdk.proj, sources/GeneratorSdk/samples/GeneratorSampleDebug/GeneratorSampleDebug.proj, sources/GeneratorSdk/sdk/sdk.props, sources/MetadataUtils/MetadataUtils.csproj, sources/PartitionUtils/PartitionUtils.csproj, sources/WinmdUtils/WinmdUtils.csproj, tests/ClangSharpSourceToWinmdTests/ClangSharpSourceToWinmdTests.csproj, tests/MetadataUtils.Tests/MetadataUtils.Tests.csproj, tests/TestCommon/TestCommon.csproj, tests/VtablesFromPdb/VtablesFromPdb.csproj, tests/Windows.Win32.Tests/Windows.Win32.Tests.csproj
- Improve discovery of VS installations
- Fix BuildSdk.proj default build
- Make it very clear that Powershell 7 is required
- Bump 5.0 SDK and runtimes to 6.0
=> Update repo SDK and build authoring

generation/WinSDK/enums.json, scripts/BaselineWinmd/Windows.Win32.winmd
=> Add SND_FLAGS and DROPEFFECT enums

generation/WinSDK/emitter.settings.rsp, scripts/BaselineWinmd/Windows.Win32.winmd
=> Add ComOutPtr attribute to D2D1CreateFactory output

generation/WinSDK/emitter.settings.rsp, scripts/BaselineWinmd/Windows.Win32.winmd
=> Mark IRestrictedErrorInfo as Agile

generation/WinSDK/enums.json
=> Add SHELL_AUTOCOMPLETE_FLAGS

generation/WinSDK/enums.json
=> Add enums for IME Constants

generation/WinSDK/Partitions/ComOle/main.cpp, scripts/BaselineWinmd/Windows.Win32.winmd
Fixes lots of in/out parameter issues in ole2.h
Fixes #941
=> Add better in/out handling for ole2.h

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
=> Adding LOGFONTW Enums

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
Changes to add enums to uxtheme methods used by winforms.
https://github.com/dotnet/winforms/issues/7468
=> Added SET_THEME_APP_PROPERTIES and changes to THEME_PROPERTY_SYMBOL_ID

scripts/ChangesSinceLastRelease.txt, sources/WinmdUtils/Program.cs, sources/WinmdUtils/Properties/launchSettings.json
When an enum is added or removed, show all enum values. This helps us know we got all the values when converting from constants to enums.
=> When showing an enum has been added or removed, show all the enum values

generation/WinSDK/emitter.settings.rsp, scripts/ChangesSinceLastRelease.txt
=> Removing inaccurate NativeArrayInfo from FormatMessage

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
=> Fix WAIT_IO_COMPLETION and WSA_WAIT_IO_COMPLETION

scripts/ChangesSinceLastRelease.txt, sources/ClangSharpSourceToWinmd/ClangSharpSourceWinmdGenerator.cs
=> Fix CM_* funcs to using PSTR/PWSTR

BuildTools/BuildTools.proj, Directory.Build.props, scripts/CommonUtils.ps1, scripts/Edit-LastReleaseVersion.ps1, tests/Windows.Win32.Tests/Windows.Win32.Tests.csproj
Add a script to edit the property for the version of the last release and clear the known changes.
=> Use a common property for the last release version.

DoAll.ps1
Clean was wiping out the last release winmd which we need at the end for the tests.
=> Fix clean problem in doall

CONTRIBUTING.md
Add `addUsesTo` section under enums in CONTRIBUTING.md
=> CONTRIBUTING.md - Add `addUsesTo` section under enums

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
Fixes: #1167
Fixes: #1168
Fixes: #1169
Fixes: #1170
Fixes: #1174
Fixes: #1175
Fixes: #1176
Fixes: #1177
Fixes: #1178
Fixes: #1179
Fixes: #1180
Fixes: #1181
```
Windows.Win32.UI.Controls.Apis.CDIS_CHECKED removed
Windows.Win32.UI.Controls.Apis.CDIS_DEFAULT removed
Windows.Win32.UI.Controls.Apis.CDIS_DISABLED removed
Windows.Win32.UI.Controls.Apis.CDIS_DROPHILITED removed
Windows.Win32.UI.Controls.Apis.CDIS_FOCUS removed
Windows.Win32.UI.Controls.Apis.CDIS_GRAYED removed
Windows.Win32.UI.Controls.Apis.CDIS_HOT removed
Windows.Win32.UI.Controls.Apis.CDIS_INDETERMINATE removed
Windows.Win32.UI.Controls.Apis.CDIS_MARKED removed
Windows.Win32.UI.Controls.Apis.CDIS_NEARHOT removed
Windows.Win32.UI.Controls.Apis.CDIS_OTHERSIDEHOT removed
Windows.Win32.UI.Controls.Apis.CDIS_SELECTED removed …
```
=> Adding enums used by winforms

generation/WinSDK/enums.json, generation/WinSDK/scraper.settings.rsp, scripts/ChangesSinceLastRelease.txt
Fixes: #1166
Fixes: #1165
Fixes: #1164
Fixes: #1163
Fixes: #1162
Fixes: #1161
Fixes: #1160
Fixes: #1158
Fixes: #1157
Fixes: #1156
Fixes: #1153
Fixes: #1151
```
Windows.Win32.Graphics.Gdi.EMR.iType...System.UInt32 => Windows.Win32.Graphics.Gdi.ENHANCED_METAFILE_RECORD_TYPE
Windows.Win32.Graphics.Gdi.ENHMETARECORD.iType...System.UInt32 => Windows.Win32.Graphics.Gdi.ENHANCED_METAFILE_RECORD_TYPE
Windows.Win32.UI.Controls.Apis.LVGIT_UNFOLDED removed
Windows.Win32.UI.Controls.Apis.LVIS_ACTIVATING removed
Windows.Win32.UI.Controls.Apis.LVIS_CUT removed
Windows.Win32.UI.Controls.Apis.LVIS_DROPHILITED removed
Windows.Win32.UI.Controls.Apis.LVIS_FOCUSED removed
Windows.Win32.UI.Controls.Apis.LVIS_GLOW removed
Windows.Win32.UI.Controls.Apis.LVIS_OVERLAYMASK removed …
```
=> Adding enums for winforms

README.md
https://github.com/microsoft/win32metadata/issues/1033
I'd still love an update on the story here :)
=> Delete C++ projection from README (was archived)

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
Adding enums for UxTheme.h.
```
Windows.Win32.UI.Controls.Apis.DrawThemeEdge : uEdge...UInt32 => DRAWEDGE_FLAGS
Windows.Win32.UI.Controls.Apis.DrawThemeEdge : uFlags...UInt32 => DRAW_EDGE_FLAGS
Windows.Win32.UI.Controls.Apis.DrawThemeText : dwTextFlags...UInt32 => DRAW_TEXT_FORMAT
Windows.Win32.UI.Controls.Apis.DrawThemeTextEx : dwTextFlags...UInt32 => DRAW_TEXT_FORMAT
Windows.Win32.UI.Controls.Apis.GetThemeTextExtent : dwTextFlags...UInt32 => DRAW_TEXT_FORMAT
Windows.Win32.UI.Controls.Apis.HitTestThemeBackground : dwOptions...UInt32 => HIT_TEST_BACKGROUND_OPTIONS
Windows.Win32.UI.Controls.Apis.HTTB_BACKGROUNDSEG removed
Windows.Win32.UI.Controls.Apis.HTTB_CAPTION removed
Windows.Win32.UI.Controls.Apis.HTTB_FIXEDBORDER removed
Windows.Win32.UI.Controls.Apis.HTTB_RESIZINGBORDER_BOTTOM …
```
=> Add enums for uxTheme.h

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
=> PICTYPE is not a flags enum.

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
=> Correct various XInput enum types

sources/ClangSharpSourceToWinmd/ClangSharpSourceWinmdGenerator.cs
Fixes: #1418 
No changes to metadata.
=> Correct EnsureEnumSizeMatchesOriginalSize switch case

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
=> Add usage hints for SWTC, SWFWO enums

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
=> Add usage hints for _SVGIO

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
=> Correct [Show|Scroll]Window statuses, commands, and flags

README.md
See also: https://github.com/microsoft/win32metadata/issues/766#issuecomment-1150295736
Fixes: #1488
@mikebattista Do double-check!
=> Clarify licensing

scripts/ChangesSinceLastRelease.txt, sources/MetadataUtils/ConstantWriter.cs, sources/MetadataUtils/ConstantsScraper.cs, sources/MetadataUtils/IConstantWriter.cs, tests/MetadataUtils.Tests/ConstantsScraperTests.cs
Fixes: #1029
Corrects #1503 changes, fixes handling of negative MAKEINTRESOURCE constants.
=> Correct ushort PSTR/PWSTR constant values

docs/projections.md
closes https://github.com/microsoft/win32metadata/issues/1543
Python Example: https://github.com/ynkdir/py-win32more/commit/a56ef040d37c1a2b18243dc3960a75f2b3ab3e05
=> VarArgs Example.

generation/WinSDK/manual/Security.Cryptography.cs, scripts/ChangesSinceLastRelease.txt
=> Add bcrypt prng functions

scripts/ChangesSinceLastRelease.txt, sources/MetadataUtils/ConstantsScraper.cs
=> Adjust scraper expression to capture BYTE constants

generation/WinSDK/enums.json, scripts/ChangesSinceLastRelease.txt
=> Adjust NOTIFYICONDATA flags, types

sources/ClangSharpSourceToWinmd/ClangSharpSourceCompilation.cs
`ClangSharpSourceToWinmd` currently uses a hard-coded path to find the `netstandard.dll` reference assembly, which is problematic if the user has a project-local version (e.g., using the [`NETStandard.Library.Ref` NuGet package](https://www.nuget.org/packages/NETStandard.Library.Ref)) or otherwise has it in a non-standard location.
Only use the hard-coded path if the compilation doesn't already have netstandard 2.1 already in the compilation: this allows users to specify a path using the normal `--ref` command line argument but falls back to the legacy behavior for customers who depend on that.
=> Only load netstandard.dll from the hardcoded path if it wasn't provided by the user

generation/WinSDK/Partitions/Direct2D/settings.rsp, scripts/ChangesSinceLastRelease.txt
=> Remove invalid D2D DWRITE_PAINT_FEATURE_LEVEL enum

generation/WinSDK/manual/WindowsAndMessaging.cs, scripts/ChangesSinceLastRelease.txt
=> Add missing resource type constants

generation/WinSDK/autoTypes.json, scripts/ChangesSinceLastRelease.txt
=> Remove errant BCRYPT_HANDLE RAII attribute

generation/WinSDK/Partitions/LibraryLoader/main.cpp, scripts/ChangesSinceLastRelease.txt
=> Add QueryOptionalDelayLoadedAPI
